= Persistence

GigaMap seamlessly integrates with {product-name}. All required type handlers are registered automatically.

== Loading

The loading process is fully automatic, as usual. Even the lazy loading is handled internally.

== Storing

After updating the contents of the GigaMap, simply call `store`, just like usual.

[source, java]
----
storageManager.store(gigaMap);
----

or this way:

[source, java]
----
gigaMap.store();
----

The GigaMap monitors changes internally, ensuring that only the modified parts are written to the storage.

This applies to all internal changes of the GigaMap as well as to added and removed entities.

Entities modified through the `update` or `apply` methods are automatically included in the store operation. There is no need to store them separately.

[source, java]
----
gigaMap.update(person, p -> {
    p.setLastName("Smith"),
    p.setAddress(newAddress)
});
gigaMap.store();
----

NOTE: Changes made to entities directly (outside of `update` or `apply`) are not tracked by the GigaMap and must be stored manually.
