= Oracle Cloud Object Storage

[source, xml, subs=attributes+]
----
<dependency>
	<groupId>org.eclipse.store</groupId>
	<artifactId>afs-oraclecloud-objectstorage</artifactId>
	<version>{maven-version}</version>
</dependency>
<dependency>
	<groupId>com.oracle.oci.sdk</groupId>
	<artifactId>oci-java-sdk-objectstorage</artifactId>
	<version>2.21.0</version>
</dependency>
----

[source, java]
----
ObjectStorageClient client = ...;
BlobStoreFileSystem fileSystem = BlobStoreFileSystem.New(
	OracleCloudObjectStorageConnector.Caching(client)
);
EmbeddedStorage.start(fileSystem.ensureDirectoryPath("storage"));
----

== Configuration

When using xref:configuration/index.adoc#external-configuration[external configuration] Oracle Cloud Object Storage can be set as follows.

[source, properties, title="eclipsestore.properties"]
----
# optional, enforces checks
storage-filesystem.target=oraclecloud.object-storage

storage-filesystem.oraclecloud.object-storage.config-file.profile=production
storage-filesystem.oraclecloud.object-storage.region=us-phoenix-1
----

[options="header",cols="1,2a,3"]
|===
|Property   
|Description   
|Type   
//-------------
|config-file.path
|The path of the config file, if not set the default is used: "~/.oci/config"
|String 

|config-file.profile
|The configuration profile to use, if not set "DEFAULT" is used.
|String  

|config-file.charset
|The encoding of the config file.
|String 

|client.connection-timeout-millis
|The max time to wait for a connection, in millis. Default is 10000.
|Integer

|client.read-timeout-millis
|The max time to wait for data, in millis. Default is 60000.
|Integer

|client.max-async-threads
|The max number of async threads to use. Default is 50.
|Integer

|region
|Sets the region to call (ex, 'us-phoenix-1').
|String

|endpoint
|Sets the endpoint to call (ex, https://www.example.com).
|String
|===

CAUTION: Depending on the amount of data and transactions, charges may apply depending on service usage. Please check with your service provider for details.
