= Convenience Methods and Explicit Storing (Transactions)

== Convenience Methods

Beside `long store(Object instance)`  {product-name} provides some convenience methods to store several objects at once:

[source, java]
----
void storeAll(Iterable<?> instances)
----

Stores the passed instance in any case and all referenced instances of persistable references recursively, but stores referenced instances only if they are newly encountered (e.g.
don't have an id associated with them in the object registry, yet and are therefore required to be handled).
This is useful for the common case of just storing an updated instance and potentially newly created instances along with it while skipping all existing (and normally unchanged) referenced instances.

[source, java]
----
List subset = myCollection.getSubset();
subset.foreach(item -> item.modify());
storage.storeAll(subset);
----

[source, java]
----
long[] storeAll(Object... instances)
----

Convenience method to store multiple instances.
The passed array (maybe implicitly created by the compiler) itself is NOT stored.

[source, java]
----
storage.storeAll(itemA, iteamB, iteamC);
----

== Transactions

[IMPORTANT]
====
{product-name} does not provide explicit transactions, every call to a store method is automatically a transaction.

*A store operation is an atomic all or nothing operation*

If the store call is successful all data is written to the storage.
Otherwise no data is persisted.
Partially persisted data will be reverted.
====

[IMPORTANT]
====
While each `store()` call is atomic at the persistence level, {product-name} does *not* synchronize the in-memory object graph for you.
In a multi-threaded application, the modification of the object graph and the corresponding `store()` call *must be done under the same lock*.
This is the application's responsibility.
Without this guarantee, another thread could read or modify the object graph between your mutation and the `store()`, leading to inconsistent in-memory or persisted state.
See xref:misc:locking/index.adoc[Locking] for details.
====

TIP: See xref:intro:concurrent-access.adoc[Concurrent Access] for the full conceptual treatment.
