package org.eclipse.store.demo.recommendations;

/*-
 * #%L
 * EclipseStore Demo Product Recommendations
 * %%
 * Copyright (C) 2023 - 2026 MicroStream Software
 * %%
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 * 
 * SPDX-License-Identifier: EPL-2.0
 * #L%
 */

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

/**
 * Entry point for the Product Recommendations demo application.
 *
 * <p>This Spring Boot application demonstrates how to use
 * {@link org.eclipse.store.gigamap.types.GigaMap GigaMap} with
 * {@link org.eclipse.store.gigamap.jvector.VectorIndex VectorIndex} to build a semantic
 * product search and recommendation engine. Products are stored in a GigaMap and indexed
 * using vector embeddings generated by an Ollama-backed LangChain4j embedding model,
 * enabling natural-language similarity queries such as "wireless headphones" to find
 * semantically related products.
 *
 * <h2>Architecture Overview</h2>
 * <ul>
 *   <li><b>Storage:</b> {@link org.eclipse.store.gigamap.types.GigaMap} provides high-performance,
 *       in-memory storage for {@link org.eclipse.store.demo.recommendations.model.Product} entities</li>
 *   <li><b>Vector Indexing:</b> {@link org.eclipse.store.gigamap.jvector.VectorIndex} maintains a
 *       similarity search index using JVector, enabling approximate nearest-neighbor (ANN) queries</li>
 *   <li><b>Embeddings:</b> {@link org.eclipse.store.demo.recommendations.vectorizer.ProductVectorizer}
 *       converts products into dense vector embeddings via an Ollama embedding model</li>
 *   <li><b>REST API:</b> {@link org.eclipse.store.demo.recommendations.controller.ProductController}
 *       exposes endpoints for listing, searching, and adding products</li>
 * </ul>
 *
 * <h2>Prerequisites</h2>
 * <ul>
 *   <li>A running Ollama instance with an embedding model (configured via {@code ollama.base-url}
 *       and {@code ollama.model-name} application properties)</li>
 *   <li>A {@code products.json} file on the classpath containing the product catalog</li>
 * </ul>
 *
 * @see org.eclipse.store.demo.recommendations.config.GigaMapConfig
 * @see org.eclipse.store.demo.recommendations.service.ProductService
 * @see org.eclipse.store.demo.recommendations.controller.ProductController
 */
@SpringBootApplication
public class ProductRecommendationsApplication
{
	/**
	 * Launches the Spring Boot application.
	 *
	 * @param args command-line arguments passed to Spring Boot
	 */
	public static void main(final String... args)
	{
		SpringApplication.run(ProductRecommendationsApplication.class, args);
	}
}
