server.port=8082
spring.application.name=vinoteca

# EclipseStore
org.eclipse.store.root=org.eclipse.store.demo.vinoteca.model.DataRoot
org.eclipse.store.storage-directory=demos/vinoteca/data
org.eclipse.store.auto-start=true

# Vaadin
vaadin.launch-browser=true
vaadin.allowed-packages=org.eclipse.store.demo.vinoteca,com.vaadin
vaadin.exclude-urls=/api/**,/graphql/**,/graphiql/**,/swagger-ui/**,/v3/api-docs/**

# Swagger / OpenAPI
springdoc.swagger-ui.try-it-out-enabled=true

# GraphQL
spring.graphql.graphiql.enabled=true
spring.graphql.graphiql.path=/graphiql
spring.graphql.schema.printer.enabled=true

# Data generation
vinoteca.initial-data-count=300
