= Welcome

Welcome to the {product-name} Reference Manual.
This manual includes concepts, instructions and examples to guide you on how to use {product-name}, version {display-version}.

You should be familiar with the Java programming language and you should have installed your preferred Integrated Development Environment (IDE).
But since you are here we guess you got that covered ;)

== What's new in {display-version}

See xref:changelog.adoc[Changelog].


== API Docs

The API documentation is available at

- https://javadoc.io/doc/org.eclipse.serializer
- https://javadoc.io/doc/org.eclipse.store


== Examples and Demo Projects

=== Examples Collection

A collection of examples with different topics:

https://github.com/eclipse-store/store/tree/master/examples

=== BookStore Demo

The BookStore Demo is a fully fledged sample application. It shows how to design an application with {product-name} from the ground up.

https://github.com/eclipse-store/bookstore-demo


== License

{product-name} is available under https://www.eclipse.org/legal/epl-2.0/[Eclipse Public License - v 2.0].
